language: scala
scala:
- 2.11.7
jdk:
- oraclejdk8
env:
  matrix:
    secure: w0QUDqquvLe7zPJofliEvnlRcnYgAivR9qriuRIys9N9SRo3t/ZYz0oAZJDLa9Xj/RF0IWkw6wBmL+jF0UVHhF++Ya8YEXIE6nc48wpVGXV9VDZFPQA8VkYCAgsraETC3GLJ1CI+CgUHp3fSnodi/rPy7QiFj22Kxn98L9EGtTL4M/Kf4ApicWlazx/CCteEXBlDnZyjdZPy3PahJKhupXkeB53CrTcrGtyyDikwf3ZxtHK4QFRBDhkRzT2H+Tzv62teusdcEpm7PHeI2f9DakE5Mr32lLci5ilKU8aqazDjDA5HtZb58jsZ9V536qUuTef7QOqjKVHv833ZNv9jbyWLkK6G5ZJgLoWeF5dMcLYvTpxSvlWSpCjEvA/j2SOKKeDp0ztIdPIKAQEUnbmYpb4Glzyl0TqXG++b4+5nypoXuDv2B7jLdknbkR88efrZstrV9rM9jMZAyyB7S7TjBtNdV6EhlYfN5HoBAhWjVjyIXCq+rca26IEtAKFpwiggcUCYVMTV1sXiZPCvJu9plP7oPwGVSjdQqbuv6CaoehZ9A/DBBcudK3Vhmb8bT+0nG5gXheh04CLWRmy6ovL2kKhpfLR4j11iBBDdqqIEW4lAPQe/7vyVWyllJcLW5feQtgU67bLsxH4d2B3wzKAkYd1EX2YCLQqeMU7q0A9exZU=
